# Generated by Django 3.1.1 on 2020-09-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255)),
                ('income', models.CharField(max_length=20)),
                ('create_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'sys_user',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
